#!/usr/bin/env python3

import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import logging
import pytz
from rich.theme import Theme
from rich.console import Console
from rich.logging import RichHandler
from datetime import datetime
import click
from typing import Tuple, List
from git import Repo, InvalidGitRepositoryError
from jinja2 import Template
from importlib.metadata import version, PackageNotFoundError

default_subdirs = [
    ".git",
    "docs",
    "src",
    ".github",
    ".github/workflows"
]

default_files = [
    "docs/README.md",
    ".gitignore",
    ".pre-commit-config.yaml",
    "pyproject.toml",
    "version.py"
]

default_github_workflows = [
    "lint.yml",
    "run_msqt.yml",
    "run_pytest.yml",
    "track_new_issues.yml",
    "track_new_prs.yml"
]

default_git_ignores = [
    "__pycache__",
    ".vscode",
    "*~",
    "*.egg-info",
    "*.#*",
    "venv/",
    ".venv/",
    "build",
    ".DS_Store",
    "log*",
    ".nfs*",
    "info.*.json",
    ".python-version"
]

default_pre_config_yaml = """
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
"""     

default_optional_requirements = [
    "ruff",
    "pre-commit",
    "pytest"
]

CONTEXT_SETTINGS = dict(help_option_names=["-h", "--help"])
CONSOLE_THEMES = Theme(
    {
        "info": "dim cyan",
        "warning": "magenta",
        "danger": "bold red"
    }
)
log_levels = {
    "CRITICAL": logging.CRITICAL,
    "ERROR": logging.ERROR,
    "WARNING": logging.WARNING,
    "INFO": logging.INFO,
    "DEBUG": logging.DEBUG,
    "NOTSET": logging.NOTSET,
}
log_format = ("%(filename)s %(name)s %(message)s")
date_time_format = "[%Y/%m/%d %H:%M:%S]"
time_zone = pytz.utc

class LoggingFormatter(logging.Formatter):
    def __init__(self):
        super().__init__(log_format, date_time_format)
        self.tz = time_zone
        self.datefmt = date_time_format

    def formatTime(self, record, datefmt):
        date_time = datetime.fromtimestamp(record.created, self.tz)
        return date_time.strftime(self.datefmt)

    def format(self, record):
        record.asctime = self.formatTime(record, self.datefmt)
        component_width = 30
        file_lineno = f"{record.filename}:{record.lineno}"
        record.filename = file_lineno.ljust(component_width)[:component_width]
        component_width = 45
        name_colon = f"{record.name}:"
        if name_colon.startswith("drunc."):
            name_colon = name_colon.replace("drunc.", "")
        record.name = name_colon.ljust(component_width)[:component_width]
        component_width = 10
        level_name = record.levelname
        record.levelname = level_name.ljust(component_width)[:component_width]
        return super().format(record)

try:
    width = os.get_terminal_size()[0]
except:
    width = 150

stdHandler = RichHandler(
    console=Console(width=width),
    omit_repeated_times=False,
    markup=True,
    rich_tracebacks=True,
    show_path=False,
    tracebacks_width=width,
)
stdHandler.setFormatter(LoggingFormatter())

log = logging.getLogger("create_python_dunedaq_package")
log.addHandler(stdHandler)

def git_is_initialized(package_path: Path) -> None:
    try:
        _ = Repo(package_path)
        return True
    except InvalidGitRepositoryError:
        return False

def validate_dot_git(package_path: Path, overwrite: bool) -> None:
    git_initialized = git_is_initialized(package_path)
    git_path = package_path / ".git"
    if git_initialized:
        return
    elif not git_initialized and git_path.exists() and not overwrite:
        log.error("Found a misconstructed '.git' directory. If this needs to be overwritten with a correctly structured git directory, use the '-o/--overwrite' option.")
        sys.exit(1)
    elif not git_initialized and git_path.exists() and overwrite:
        log.warning("Found improperly formatted .git, overwriting it.")
        shutil.rmtree(git_path)
    Repo.init(package_path, mkdir=True)
    return

def in_dot_git(git_dir: Path, obj: Path) -> bool:
    obj = obj.resolve()
    git_dir = git_dir.resolve()
    try:
        obj.relative_to(git_dir)
        return True
    except ValueError:
        return False

def wipe_directory(
        package_path: Path,
        applications: list[str],
        schema: bool, 
        clean: bool,
        overwrite: bool
    ) -> None:
    """Minimize the package directory. 
    If clean, removes the non-standard directories.
    If overwrite, removes all directories aside from .git.
    """
    validate_dot_git(package_path, overwrite)
    git_dir = package_path / ".git"

    if overwrite:
        for item in package_path.iterdir():
            if item == git_dir:
                continue
            if item.is_dir():
                log.warning(f"Removing directory {item}")
                shutil.rmtree(item)
            else:
                log.warning(f"Removing file {item}")
                item.unlink()
        return

    package_name = package_path.name
    keep_dirs = [package_path / path for path in default_subdirs]
    keep_dirs.append(package_path / "src" / package_name)
    keep_dirs.append(package_path / "src" / package_name / "tests")
    if applications:
        keep_dirs.append(package_path / "src" / package_name / "apps")
    if schema:
        keep_dirs.append(package_path / "schema")
        keep_dirs.append(package_path / "src" / package_name / "schema")
    log.debug(f"Handling directories: {[str(d) for d in keep_dirs]}")

    for dir in [d for d in package_path.rglob("*") if d.is_dir()]:
        log.debug(f"Handling directory {dir}")
        if dir not in keep_dirs and clean and not in_dot_git(git_dir, dir):
            log.warning(f"Removing directory {dir}")
            shutil.rmtree(dir)
        else:
            log.info(f"Found directory {dir}, leaving as is.")

    keep_files = [package_path / path for path in default_files]
    keep_files.extend([p / "__init__.py" for p in (package_path / "src" / package_name).rglob("*") if p.is_dir()])
    log.debug(f"Handling files: {[str(d) for d in keep_files]}")
    if (package_path / "README.md").is_file():
        log.info("Found README.md in the root, not removing it.")
        keep_files.append(package_path / "README.md")

    for file in [f for f in package_path.rglob("*") if f.is_file()]:
        log.debug(f"Handling file {file}")
        if not in_dot_git(git_dir, file):
            if file not in keep_files and clean:
                    log.warning(f"Removing file {file}")
                    file.unlink()
            else:
                log.info(f"Found file {file}, leaving as is.")
    return

def make_subdirs(package_path: Path, applications: tuple[str], schema: bool) -> None:
    package_name = package_path.name
    create_subdirs = [package_path / dir for dir in default_subdirs]
    create_subdirs.append(package_path / "src" / package_name / "tests")
    if applications or schema:
        create_subdirs.append(package_path / "src" / package_name / "apps")
    if schema:
        create_subdirs.extend(package_path / dir for dir in ["schema", f"src/{package_name}/schema"])
    for dir in create_subdirs:
        if not dir.exists():
            log.info(f"Generating directory {dir}")
            dir.mkdir(parents=True)
    return

def construct_file(file: Path, overwrite: bool) -> bool: 
    if file.is_file():
        if not overwrite:
            log.info(f"File {file} already exists, and overwrite has not been set.")
            return False
        else:
            log.info(f"File {file} already exists, removing file")
            file.unlink()
            return True
    else:
        log.debug(f"File does not exist, write the file {file}.")
        return True

def construct_default_readme_md(
        package_path: Path,
        description: str,
        overwrite: bool
    ) -> None:
    file = package_path / "docs" / "README.md"
    if not construct_file(file, overwrite):
        return
    package_name = package_path.name
    log.info(f"Writing {file.name}")
    with file.open(mode='w') as f:
        f.write(f'# {package_name}\n{description}\n')
    return

def construct_default_gitignore(package_path: Path, overwrite: bool) -> None:
    file = package_path / ".gitignore"
    if not construct_file(file, overwrite):
        return
    log.info(f"Writing {file.name}")
    with file.open(mode='w') as f:
        f.write("\n".join(default_git_ignores))
    return

def construct_default_github_workflows(
    package_path: Path,
    overwrite: bool
) -> None:
    template_workflow_dir = Path(os.getenv("DAQ_CMAKE_SHARE")) / "config" / "templates" / "python" / "github_workflows"
    workflow_files = [file for file in template_workflow_dir.iterdir() if file.is_file()]
    destination = package_path / ".github" / "workflows"
    for file in workflow_files:
        if not construct_file(destination / file.name, overwrite):
            continue
        shutil.copy(file, destination)
        log.info(f"Template .github/workflow file {file} has been written to {destination}")
    return

def construct_default_pre_commit_config_yaml(package_path: Path, overwrite: bool) -> None:
    file = package_path / ".pre-commit_config.yaml"
    if not construct_file(file, overwrite):
        return
    log.info(f"Writing {file.name}")
    with file.open(mode='w') as f:
        f.write(default_pre_config_yaml)
    return

def construct_default_version_py(package_path: Path, overwrite: bool) -> None:
    file = package_path / "version.py"
    if not construct_file(file, overwrite):
        return
    log.info(f"Writing {file.name}")
    with file.open(mode='w') as f:
        f.write(f'"""Version number for package {package_path.name}."""\n__version__ = "0.0.0"')
    return

def construct_application_file(
        daq_cmake_share: Path,
        application: str,
        application_path: Path,
        overwrite: bool
    ) -> None:
    if not construct_file(application_path, overwrite):
        return
    default_application_path = daq_cmake_share / "config" / "templates" / "python" / "python_application_template.txt"
    template = Template(default_application_path.read_text())
    params = {"APPLICATION" : application}
    result = template.render(**params)
    application_path.write_text(result)
    log.info(f"File {application_path} for application {application} written")
    return

def construct_default_schema_compile(
        daq_cmake_share: Path,
        application: str,
        application_path: Path,
        overwrite: bool
    ) -> None:
    if not construct_file(application_path, overwrite):
        return
    default_application_path = daq_cmake_share / "config" / "templates" / "python" / "generate_protos_template.txt"
    template = Template(default_application_path.read_text())
    params = {
        "APPLICATION" : application
    }
    result = template.render(**params)
    application_path.write_text(result)
    log.info(f"File {application_path} for application {application} written")
    return

def construct_default_proto(
    daq_cmake_share: Path,
    package_path: Path,
    overwrite: bool
) -> None:
    file = package_path / "schema" / "template.proto"
    if not construct_file(file, overwrite):
        return
    default_proto_file_name = "renameme_info.proto"
    default_proto_path = daq_cmake_share / "config" / "templates" / default_proto_file_name
    shutil.copy(default_proto_path, file)
    log.info(f"Template protobuf file {default_proto_file_name} has been written to {file}")
    return

def parse_applications(package_path: Path, applications: List[str], daq_cmake_share: Path, schema: bool, overwrite: bool) -> str:
    template_entry_points = '[project.scripts]'
    package_name = package_path.name
    for application in applications:
        application_path = f"{package_name}/apps/__main_{application}__"
        construct_application_file(
            daq_cmake_share,
            application,
            package_path / "src" / (application_path + ".py"),
            overwrite
        )
        application_entry_point = f"{application_path.replace('/', '.')}:main"
        template_entry_points += f'\n{application} = {application_entry_point}'
        log.info(f"Added application {application} to pyproject.toml")

    if schema:
        application = package_name + "_generate_protos"
        application_path = f"{package_name}/apps/__main_{application}__"
        construct_default_schema_compile(
            daq_cmake_share,
            application,
            package_path / "src" / (application_path + ".py"),
            overwrite
        )
        construct_default_proto(
            daq_cmake_share,
            package_path,
            overwrite
        )
        application_entry_point = f"{application_path.replace('/', '.')}:main"
        template_entry_points += f'\n{application} = "{application_entry_point}"'

    return template_entry_points

def format_requirements(requirements: list[str]) -> list[str]:
    formatted_requirements = []
    requirement_pattern_with_version = r'^[a-zA-Z0-9_-]+==\d+\.\d+\.\d+$'
    requirement_pattern_without_version = r'^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$'
    log.debug(f"Processing requirements: {requirements}")
    for requirement in requirements:
        if bool(re.match(requirement_pattern_with_version, requirement)):
            package_name, requested_package_version = requirement.split("==")
        elif bool(re.match(requirement_pattern_without_version, requirement)):
            package_name = requirement
            requested_package_version = ""
        else:
            log.error(f"Requirement '{requirement}' improperly formatted, expected a package name or a package name with version number.")
            sys.exit(1)

        try:
            available_package_version = version(package_name)
            if available_package_version == requested_package_version:
                log.debug(f"{requirement} found with requested version")
                formatted_requirements.append(requirement)
            else:
                log.info(f"Package {package_name} requested with version {requested_package_version}, but found installed version {available_package_version}. Using this version.")
                formatted_requirements.append(f"{package_name}=={available_package_version}")
        except PackageNotFoundError:
            log.error(f"Package {package_name} not found in environment, skipping.")
            sys.exit(1)
    return formatted_requirements

def construct_default_pyproject_toml(
        package_path: Path,
        package_description: str,
        requirements: List[str],
        applications: tuple[str],
        schema: bool,
        overwrite: bool
    ) -> None:
    file = package_path / "pyproject.toml"
    package_name = package_path.name
    daq_cmake_share = Path(os.getenv("DAQ_CMAKE_SHARE"))
    if not daq_cmake_share:
        raise OSError("$DAQ_CMAKE_SHARE not found, exiting.")
    template_path = Path(daq_cmake_share) / "config" / "templates" / "python" / "pyproject_template.txt"
    template = Template(template_path.read_text())
    template_params = {
        "PACKAGE_NAME" : package_name,
        "DESCRIPTION" : package_description
    }
    optional_requirements = default_optional_requirements
    if applications or schema:
        template_params["APPLICATIONS"] = parse_applications(package_path, applications, daq_cmake_share, schema, overwrite)
        log.info(f"Added all script entry points")

    if schema:
        ruff_exclude_dirs = [
            package_name + "/" + package_name + ".egg-info",
            package_name + "/src/schema/*._pb2.py*",
            package_name + "/src/schema/*._pb2_grpc.py*"
        ]
        ruff_exclude_dirs_str = "[tool.ruff]\nexclude = [\n" + "\n".join(f'"{dir}",' for dir in ruff_exclude_dirs) + "\n]"
        template_params["RUFF_EXCLUDE"] = ruff_exclude_dirs_str
        requirements = list(requirements)
        requirements.extend(["grpcio", "grpcio-status", "grpcio-tools", "googleapis-common-protos"])
        optional_requirements.extend(["mypy-protobuf", "types-protobuf"])
    
    if requirements:
        requirements = format_requirements(requirements)
        requirements_str = "dependencies = [\n" + "\n".join(f'"{pkg}",' for pkg in requirements) + "\n]"
        template_params["DEPENDENCIES"] =  requirements_str 

    optional_requirements_str = "[project.optional-dependencies] \ndev = [" + ", ".join(f'"{pkg}"' for pkg in optional_requirements) + "]"
    print(optional_requirements_str)
    template_params["OPTIONAL_DEPENDENCIES"] = optional_requirements_str

    log.info(template_params)
    log.info(template.render(**template_params))
    file.write_text(template.render(**template_params))
    return

def make_files(
        package_path: Path,
        overwrite: bool,
        requirements: tuple[str],
        applications: tuple[str],
        package_description: str,
        schema: bool
    ) -> None:
    construct_default_readme_md(package_path, package_description, overwrite)
    construct_default_gitignore(package_path, overwrite)
    construct_default_github_workflows(package_path, overwrite)
    construct_default_version_py(package_path, overwrite)
    construct_default_pre_commit_config_yaml(package_path, overwrite)
    construct_default_pyproject_toml(
        package_path,
        package_description,
        requirements,
        applications,
        schema,
        overwrite
    )
    return

@click.command()
@click.argument("package-name", nargs=1, type=str)
@click.option(
    "-l",
    "--log-level",
    type=click.Choice(log_levels.keys(), case_sensitive=False),
    default="INFO",
    help="Set the log level.",
)
@click.option(
    "-c",
    "--clean",
    is_flag=True,
    help="Remove all existing files and directories that do not follow the standard python package structure."
)
@click.option(
    "-o",
    "--overwrite",
    is_flag=True,
    help="Overwrite existing files required for the standard python package structure. Does not affect .git."
)
@click.option(
    "-r",
    "--requirement",
    "requirements",
    multiple=True,
    help="Define requiements for the pyproject.toml as e.g. 'click==8.1.7'"
)
@click.option(
    "-a",
    "--app",
    "applications",
    multiple=True,
    help="Create template scripts for applications to become available when installed"
)
@click.option(
    "-s",
    "--schema",
    is_flag=True,
    help="Makes a directory to include all the schema files and include a script to compile the schema into *pb2.py, *pb2.pyi, and *pb2_grpc.pb2."
)
@click.option(
    "-p",
    "--package-description",
    type=str,
    help="Package description for the pyproject.toml."
)
def create_python_dunedaq_package(
    package_name: str,
    log_level: str,
    clean: bool,
    overwrite: bool,
    requirements: tuple[str],
    applications: tuple[str],
    schema: bool,
    package_description: str) -> None:
    """Create new DUNEDAQ python package.
This script generates much of the standard python code of a new DUNE DAQ package.
Simplest usage:\n\n\tcreate_python_dunedaq_package <package_name>\n
The directory out of which you run this script must be empty with the possible
exception of a git/ version control subdirectory.\n
In the instance that you have an existing repository, you can validate that it follows
the correct structure with the same command. To overwrite the existing code to ensure
that the package follows the correct structure, use the -o/--overwrite option.
To remove code that does not follow the correct structure, use the -c/--clean option.\n
For details on how to write a DUNE DAQ package, please look at the official daq-cmake
documentation at https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-cmake/.\n
For details on how to write a python-only DUNE DAQ package, please look at the official
daq-cmake documentation at
https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-cmake/python-only-packages.
    """
    log.setLevel(log_levels[log_level])
    if package_name == ".":
        parent_directory = Path.cwd().parent
        log.error(
            "You passed \".\" as the name of the package. What I *think* you want " \
            "to do is cd up one directory and pass the name of this subdirectory " \
            f"{parent_directory} as the argument"
        )
        sys.exit(1)
    if not re.search(r"^[a-z][_a-z0-9]+$", package_name):
        log.error(
            f"The asked-for package name of \"{package_name}\" doesn't satisfy the " \
            "requirement that the package begin with a lowercase letter and consist " \
            "only of lowercase letters, underscores and numbers"
        )
        sys.exit(1)
    for application in applications:
        if not re.fullmatch(r"[a-z]+(_[a-z]+)*", application):
            log.error(
                f"""
Requested user application name \"{application}\" needs to be in snake_case. 
Please see https://dune-daq-sw.readthedocs.io/en/latest/packages/styleguide/ 
for more on naming conventions. Exiting...
""")
    package_path = Path.cwd() / Path(package_name)
    
    if not package_path.exists() or (package_path.exists() and package_path.is_file()):
        log.info(f"Creating path {package_path}")
        package_path.mkdir()

    if package_description is None:
        package_description = "Description left as an exercise for the author"

    wipe_directory(package_path, applications, schema, clean, overwrite)
    make_subdirs(package_path, applications, schema)
    make_files(
        package_path,
        overwrite,
        requirements,
        applications,
        package_description,
        schema
    )
    return


if __name__ == '__main__':
    create_python_dunedaq_package()
