#!/usr/bin/env python3

import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import logging
import pytz
from rich.theme import Theme
from rich.console import Console
from rich.logging import RichHandler
from datetime import datetime
import click
from typing import Tuple, List
from git import Repo, InvalidGitRepositoryError
from jinja2 import Template

default_subdirs = [
    ".git",
    "docs",
    "src",
    ".github"
]
default_files = [
    "docs/README.md",
    ".gitignore",
    ".pre-commit-config.yaml",
    "pyproject.toml",
    "version.py"
]

default_git_ignores = [
    "__pycache__",
    ".vscode",
    "*~",
    "*.egg-info",
    "*.#*",
    "venv/",
    ".venv/",
    "build",
    ".DS_Store",
    "log*",
    ".nfs*",
    "info.*.json",
    ".python-version"
]

default_pre_config_yaml = """
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
"""     

CONTEXT_SETTINGS = dict(help_option_names=["-h", "--help"])
CONSOLE_THEMES = Theme(
    {
        "info": "dim cyan",
        "warning": "magenta",
        "danger": "bold red"
    }
)
log_levels = {
    "CRITICAL": logging.CRITICAL,
    "ERROR": logging.ERROR,
    "WARNING": logging.WARNING,
    "INFO": logging.INFO,
    "DEBUG": logging.DEBUG,
    "NOTSET": logging.NOTSET,
}
log_format = ("%(filename)s %(name)s %(message)s")
date_time_format = "[%Y/%m/%d %H:%M:%S]"
time_zone = pytz.utc

class LoggingFormatter(logging.Formatter):
    def __init__(self):
        super().__init__(log_format, date_time_format)
        self.tz = time_zone
        self.datefmt = date_time_format

    def formatTime(self, record, datefmt):
        date_time = datetime.fromtimestamp(record.created, self.tz)
        return date_time.strftime(self.datefmt)

    def format(self, record):
        record.asctime = self.formatTime(record, self.datefmt)
        component_width = 30
        file_lineno = f"{record.filename}:{record.lineno}"
        record.filename = file_lineno.ljust(component_width)[:component_width]
        component_width = 45
        name_colon = f"{record.name}:"
        if name_colon.startswith("drunc."):
            name_colon = name_colon.replace("drunc.", "")
        record.name = name_colon.ljust(component_width)[:component_width]
        component_width = 10
        level_name = record.levelname
        record.levelname = level_name.ljust(component_width)[:component_width]
        return super().format(record)

try:
    width = os.get_terminal_size()[0]
except:
    width = 150

stdHandler = RichHandler(
    console=Console(width=width),
    omit_repeated_times=False,
    markup=True,
    rich_tracebacks=True,
    show_path=False,
    tracebacks_width=width,
)
stdHandler.setFormatter(LoggingFormatter())

log = logging.getLogger("create_python_dunedaq_package")
log.addHandler(stdHandler)

def git_is_initialized(package_path: Path) -> None:
    try:
        _ = Repo(package_path)
        return True
    except InvalidGitRepositoryError:
        return False

def validate_dot_git(package_path: Path, force: bool) -> None:
    git_initialized = git_is_initialized(package_path)
    git_path = package_path / ".git"
    if git_initialized:
        return
    elif not git_initialized and git_path.exists() and not force:
        log.error(
"Found a misconstructed '.git' directory. If this needs to be overwritten with a " \
"correctly structured git directory, use the '-f/--force' option."
                )
        sys.exit(1)
    elif not git_initialized and git_path.exists() and force:
        shutil.rmtree(package_path)
    repo = Repo.init(package_path, mkdir=True)
    return

def wipe_package_directory(package_path: Path, force: bool) -> None:
    validate_dot_git(package_path)
    keep_dirs = [package_path / path for path in default_subdirs]
    for dir in package_path.iterdir():
        if dir.is_dir() and dir not in keep_dirs:
            if not force:
                log.error(f"Directory {dir} found, but force not enabled.")
                sys.exit(1)
            log.warning(f"Removing directory {dir}")
            shutil.rmtree(dir)
    keep_files = [package_path / path for path in default_files]
    for file in package_path.iterdir():
        if file.is_file() and file not in keep_files:
            if not force:
                log.error(f"File {file} found, but force not enabled.")
                sys.exit(1)
            log.warning(f"Removing file {file}")
            file.unlink()
    return

def make_package_subdirs(package_path: Path, schema: bool) -> None:
    if not package_path.is_dir():
        raise IsADirectoryError(f"{package_path} doesn't point to a directory.")
    package_name = package_path.name
    create_subdirs = [package_path / dir for dir in default_subdirs]
    create_subdirs.append(f"src/{package_name}/tests")
    if schema:
        create_subdirs.append(f"schema/{package_name}")
    for dir in create_subdirs:
        if not dir.exists():
            log.info(f"Generating directory {dir}")
            dir.mkdir(parents=True)
    return

def construct_application_file(
        daq_cmake_share: Path,
        application: str,
        application_path: Path,
        force: bool
    ) -> None:
    if application_path.is_file() and not force:
        log.info(f"File for application {application} ({application_path}) already exists, skipping")
        return
    elif application_path.is_file() and force:
        log.warning(f"File for application {application} ({application_path}) already exists, overwriting")
        application_path.unlink()
    
    default_application_path = daq_cmake_share / "config" / "templates" / "python_application_template.txt"
    default_application_str = default_application_path.read_text()

    template = Template(default_application_str)
    params = {"APPLICATION" : application}
    result = template.render(**params)
    application_path.write_text(result)
    log.info(f"Written the file {application_path} for application {application}")
    return

def construct_default_pyproject_toml(
        package_path: Path,
        package_description: str,
        dependencies: List[str],
        applications: Tuple[str],
        force: bool
    ) -> None:
    file = package_path / "pyproject.toml"
    daq_cmake_share = os.getenv("DAQ_CMAKE_SHARE")
    if not template_path:
        raise OSError("$DAQ_CMAKE_SHARE not found, exiting.")
    template_path = Path(daq_cmake_share) / "config" / "templates" 
    template_path = template_path / "pyproject_template.txt" #RETURNTOME

    pyproject_toml_str = template_path.read_text()
    template = Template(pyproject_toml_str)
    params = {
        "PACKAGE_NAME" : package_path.name,
        "DESCRIPTION" : package_description,
        "DEPENDENCIES" : dependencies
    }
    result = template.render(**params)
    if len(applications):
        entry_points = '[project.scripts]'
        package_name = package_path.name
        for application in applications:
            application_path = f"{package_name}/apps/__main_{application}__"
            construct_application_file(
                daq_cmake_share,
                application,
                Path(application_path + ".py"),
                force
            )
            application_entry_point = f"{application_path.replace("/", ".")}:main"
            entry_points += f'\n{application}: "{application_entry_point}'
            log.info(f"Added application {application} to pyproject.toml")
    return

def construct_default_gitignore(package_path: Path) -> None:
    file = package_path / ".gitignore"
    with file.open(mode='w') as f:
        f.write("\n".join(default_git_ignores))
    return

def construct_default_pre_commit_config_yaml(package_path: Path) -> None:
    file = package_path / ".pre-commit_config.yaml"
    with file.open(mode='w') as f:
        f.write(default_pre_config_yaml)
    return

def construct_default_version_py(package_path: Path) -> None:
    file = package_path / "version.py"
    with file.open(mode='w') as f:
        f.write('__version__ = "0.0.0"')
    return

def construct_default_readme_md(package_path: Path, description: str) -> None:
    file = package_path / "docs" / "README.md"
    package_name = package_path.name
    with file.open(mode='w') as f:
        f.write(f'# {package_name}\n{description}')
    return


@click.command()
@click.argument("package-name", nargs=1, type=str)
@click.option(
    "-l",
    "--log-level",
    type=click.Choice(log_levels.keys(), case_sensitive=False),
    default="INFO",
    help="Set the log level",
)
@click.option(
    "-f",
    "--force",
    is_flag=True,
    help="Remove all existing files and directories that do not follow the standard" \
    "python package structure"
)
@click.option(
    "-r",
    "--requirement",
    "requirements",
    multiple=True,
    help="Defines the requiements for the pyproject.toml as e.g. 'click==8.1.7'"
)
@click.option(
    "-a",
    "--app",
    "applications",
    multiple=True,
    help="Defines the repository scripts available when installed"
)
@click.option(
    "-s",
    "--schema",
    is_flag=True,
    help="If true, includes a scrpt to compile the schema into *pb2.py, *pb2.pyi, " \
    "and *pb2_grpc.pb2."
)
@click.option(
    "-p",
    "--package-description",
    type=str,
    help="Package description for the pyproject.toml."
)
def create_python_dunedaq_package(
    package_name: str,
    log_level: str,
    force: bool,
    requirements: Tuple(str),
    applications: Tuple(str),
    schema: bool,
    package_description: str):
    """Create new DUNEDAQ python package.
This script generates much of the standard python code of a new DUNE DAQ package.
Simplest usage:\n\n\tcreate_python_dunedaq_package <package_name>\n
The directory out of which you run this script must be empty with the possible
exception of a git/ version control subdirectory.\n
For details on how to write a DUNE DAQ package, please look at the official daq-cmake
documentation at https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-cmake/.\n
For details on how to write a python-only DUNE DAQ package, please look at the official
daq-cmake documentation at
https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-cmake/python-only-packages.
    """
    log.setLevel(log_levels[log_level])
    if package_name == ".":
        log.error(
            "You passed \".\" as the name of the package. What I *think* you want " \
            "to do is cd up one directory and pass the name of this subdirectory " \
            f"{parent_directory} as the argument"
        )
        sys.exit(1)
    if not re.search(r"^[a-z][_a-z0-9]+$", package_name):
        log.error(
            f"The asked-for package name of \"{package_name}\" doesn't satisfy the " \
            "requirement that the package begin with a lowercase letter and consist " \
            "only of lowercase letters, underscores and numbers"
        )
        sys.exit(1)
    for application in applications:
        if not re.fullmatch(r"[a-z]+(_[a-z]+)*", application):
            log.error(
                f"""
Requested user application name \"{application}\" needs to be in snake_case. 
Please see https://dune-daq-sw.readthedocs.io/en/latest/packages/styleguide/ 
for more on naming conventions. Exiting...
""")
    package_path = Path.cwd() / Path(package_name)
    
    if not package_path.exists() or (package_path.exists() and package_path.is_file()):
        log.info(f"Creating path {package_path}")
        package_path.mkdir()

    wipe_package_directory(package_path, force)
    make_package_subdirs(package_path)
    sys.exit(0)


if __name__ == '__main__':
    create_python_dunedaq_package()
